return {
	AssetsFolderName = "Assets",
	CreaturesFolderName = "Creatures",
	TierOrder = { "Common", "Rare", "Epic", "Legendary", "Mythic", "Wild" },
	Items = {
		{
			Id = "01_Neon_Fox",
			Index = 1,
			Name = "Neon Fox",
			Category = "Pet",
			Tier = "Common",
			Behavior = "Pet companion",
			Accent = "cyan",
			Secondary = "orange",
			ModelName = "01_Neon_Fox",
			ModelPath = "Assets/Creatures/Pets/Common/01_Neon_Fox",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Common/01_Neon_Fox/Neon_Fox.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Common/01_Neon_Fox/Neon_Fox.obj",
		},
		{
			Id = "02_Neon_Wolf",
			Index = 2,
			Name = "Neon Wolf",
			Category = "Pet",
			Tier = "Common",
			Behavior = "Pet companion",
			Accent = "blue",
			Secondary = "cyan",
			ModelName = "02_Neon_Wolf",
			ModelPath = "Assets/Creatures/Pets/Common/02_Neon_Wolf",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Common/02_Neon_Wolf/Neon_Wolf.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Common/02_Neon_Wolf/Neon_Wolf.obj",
		},
		{
			Id = "03_Crystal_Rabbit",
			Index = 3,
			Name = "Crystal Rabbit",
			Category = "Pet",
			Tier = "Common",
			Behavior = "Pet companion",
			Accent = "pink",
			Secondary = "cyan",
			ModelName = "03_Crystal_Rabbit",
			ModelPath = "Assets/Creatures/Pets/Common/03_Crystal_Rabbit",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Common/03_Crystal_Rabbit/Crystal_Rabbit.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Common/03_Crystal_Rabbit/Crystal_Rabbit.obj",
		},
		{
			Id = "04_Arcane_Cat",
			Index = 4,
			Name = "Arcane Cat",
			Category = "Pet",
			Tier = "Common",
			Behavior = "Pet companion",
			Accent = "purple",
			Secondary = "magenta",
			ModelName = "04_Arcane_Cat",
			ModelPath = "Assets/Creatures/Pets/Common/04_Arcane_Cat",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Common/04_Arcane_Cat/Arcane_Cat.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Common/04_Arcane_Cat/Arcane_Cat.obj",
		},
		{
			Id = "05_Electric_Owl",
			Index = 5,
			Name = "Electric Owl",
			Category = "Pet",
			Tier = "Common",
			Behavior = "Pet companion",
			Accent = "gold",
			Secondary = "cyan",
			ModelName = "05_Electric_Owl",
			ModelPath = "Assets/Creatures/Pets/Common/05_Electric_Owl",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Common/05_Electric_Owl/Electric_Owl.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Common/05_Electric_Owl/Electric_Owl.obj",
		},
		{
			Id = "06_Cyber_Hawk",
			Index = 6,
			Name = "Cyber Hawk",
			Category = "Pet",
			Tier = "Rare",
			Behavior = "Pet companion",
			Accent = "cyan",
			Secondary = "gold",
			ModelName = "06_Cyber_Hawk",
			ModelPath = "Assets/Creatures/Pets/Rare/06_Cyber_Hawk",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Rare/06_Cyber_Hawk/Cyber_Hawk.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Rare/06_Cyber_Hawk/Cyber_Hawk.obj",
		},
		{
			Id = "07_Void_Panther",
			Index = 7,
			Name = "Void Panther",
			Category = "Pet",
			Tier = "Rare",
			Behavior = "Pet companion",
			Accent = "purple",
			Secondary = "magenta",
			ModelName = "07_Void_Panther",
			ModelPath = "Assets/Creatures/Pets/Rare/07_Void_Panther",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Rare/07_Void_Panther/Void_Panther.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Rare/07_Void_Panther/Void_Panther.obj",
		},
		{
			Id = "08_Spirit_Deer",
			Index = 8,
			Name = "Spirit Deer",
			Category = "Pet",
			Tier = "Rare",
			Behavior = "Pet companion",
			Accent = "green",
			Secondary = "cyan",
			ModelName = "08_Spirit_Deer",
			ModelPath = "Assets/Creatures/Pets/Rare/08_Spirit_Deer",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Rare/08_Spirit_Deer/Spirit_Deer.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Rare/08_Spirit_Deer/Spirit_Deer.obj",
		},
		{
			Id = "09_Thunder_Tiger",
			Index = 9,
			Name = "Thunder Tiger",
			Category = "Pet",
			Tier = "Rare",
			Behavior = "Pet companion",
			Accent = "gold",
			Secondary = "blue",
			ModelName = "09_Thunder_Tiger",
			ModelPath = "Assets/Creatures/Pets/Rare/09_Thunder_Tiger",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Rare/09_Thunder_Tiger/Thunder_Tiger.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Rare/09_Thunder_Tiger/Thunder_Tiger.obj",
		},
		{
			Id = "10_Lava_Salamander",
			Index = 10,
			Name = "Lava Salamander",
			Category = "Pet",
			Tier = "Rare",
			Behavior = "Pet companion",
			Accent = "orange",
			Secondary = "red",
			ModelName = "10_Lava_Salamander",
			ModelPath = "Assets/Creatures/Pets/Rare/10_Lava_Salamander",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Rare/10_Lava_Salamander/Lava_Salamander.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Rare/10_Lava_Salamander/Lava_Salamander.obj",
		},
		{
			Id = "11_Crystal_Dragonling",
			Index = 11,
			Name = "Crystal Dragonling",
			Category = "Pet",
			Tier = "Epic",
			Behavior = "Pet companion",
			Accent = "cyan",
			Secondary = "purple",
			ModelName = "11_Crystal_Dragonling",
			ModelPath = "Assets/Creatures/Pets/Epic/11_Crystal_Dragonling",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Epic/11_Crystal_Dragonling/Crystal_Dragonling.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Epic/11_Crystal_Dragonling/Crystal_Dragonling.obj",
		},
		{
			Id = "12_Cosmic_Whale",
			Index = 12,
			Name = "Cosmic Whale",
			Category = "Pet",
			Tier = "Epic",
			Behavior = "Pet companion",
			Accent = "purple",
			Secondary = "cyan",
			ModelName = "12_Cosmic_Whale",
			ModelPath = "Assets/Creatures/Pets/Epic/12_Cosmic_Whale",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Epic/12_Cosmic_Whale/Cosmic_Whale.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Epic/12_Cosmic_Whale/Cosmic_Whale.obj",
		},
		{
			Id = "13_Phoenix_Cub",
			Index = 13,
			Name = "Phoenix Cub",
			Category = "Pet",
			Tier = "Epic",
			Behavior = "Pet companion",
			Accent = "orange",
			Secondary = "gold",
			ModelName = "13_Phoenix_Cub",
			ModelPath = "Assets/Creatures/Pets/Epic/13_Phoenix_Cub",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Epic/13_Phoenix_Cub/Phoenix_Cub.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Epic/13_Phoenix_Cub/Phoenix_Cub.obj",
		},
		{
			Id = "14_Shadow_Lynx",
			Index = 14,
			Name = "Shadow Lynx",
			Category = "Pet",
			Tier = "Epic",
			Behavior = "Pet companion",
			Accent = "magenta",
			Secondary = "purple",
			ModelName = "14_Shadow_Lynx",
			ModelPath = "Assets/Creatures/Pets/Epic/14_Shadow_Lynx",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Epic/14_Shadow_Lynx/Shadow_Lynx.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Epic/14_Shadow_Lynx/Shadow_Lynx.obj",
		},
		{
			Id = "15_Celestial_Lion",
			Index = 15,
			Name = "Celestial Lion",
			Category = "Pet",
			Tier = "Epic",
			Behavior = "Pet companion",
			Accent = "gold",
			Secondary = "white",
			ModelName = "15_Celestial_Lion",
			ModelPath = "Assets/Creatures/Pets/Epic/15_Celestial_Lion",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Epic/15_Celestial_Lion/Celestial_Lion.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Epic/15_Celestial_Lion/Celestial_Lion.obj",
		},
		{
			Id = "16_Ancient_Turtle",
			Index = 16,
			Name = "Ancient Turtle",
			Category = "Pet",
			Tier = "Legendary",
			Behavior = "Pet companion",
			Accent = "green",
			Secondary = "gold",
			ModelName = "16_Ancient_Turtle",
			ModelPath = "Assets/Creatures/Pets/Legendary/16_Ancient_Turtle",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Legendary/16_Ancient_Turtle/Ancient_Turtle.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Legendary/16_Ancient_Turtle/Ancient_Turtle.obj",
		},
		{
			Id = "17_Neon_Griffin",
			Index = 17,
			Name = "Neon Griffin",
			Category = "Pet",
			Tier = "Legendary",
			Behavior = "Pet companion",
			Accent = "cyan",
			Secondary = "gold",
			ModelName = "17_Neon_Griffin",
			ModelPath = "Assets/Creatures/Pets/Legendary/17_Neon_Griffin",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Legendary/17_Neon_Griffin/Neon_Griffin.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Legendary/17_Neon_Griffin/Neon_Griffin.obj",
		},
		{
			Id = "18_Void_Serpent",
			Index = 18,
			Name = "Void Serpent",
			Category = "Pet",
			Tier = "Legendary",
			Behavior = "Pet companion",
			Accent = "purple",
			Secondary = "magenta",
			ModelName = "18_Void_Serpent",
			ModelPath = "Assets/Creatures/Pets/Legendary/18_Void_Serpent",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Legendary/18_Void_Serpent/Void_Serpent.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Legendary/18_Void_Serpent/Void_Serpent.obj",
		},
		{
			Id = "19_Star_Dragon",
			Index = 19,
			Name = "Star Dragon",
			Category = "Pet",
			Tier = "Mythic",
			Behavior = "Pet companion",
			Accent = "white",
			Secondary = "cyan",
			ModelName = "19_Star_Dragon",
			ModelPath = "Assets/Creatures/Pets/Mythic/19_Star_Dragon",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Mythic/19_Star_Dragon/Star_Dragon.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Mythic/19_Star_Dragon/Star_Dragon.obj",
		},
		{
			Id = "20_Galaxy_Unicorn",
			Index = 20,
			Name = "Galaxy Unicorn",
			Category = "Pet",
			Tier = "Mythic",
			Behavior = "Pet companion",
			Accent = "pink",
			Secondary = "purple",
			ModelName = "20_Galaxy_Unicorn",
			ModelPath = "Assets/Creatures/Pets/Mythic/20_Galaxy_Unicorn",
			FbxPath = "Roblox_NeonFantasyCreatures/Pets/Mythic/20_Galaxy_Unicorn/Galaxy_Unicorn.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/Pets/Mythic/20_Galaxy_Unicorn/Galaxy_Unicorn.obj",
		},
		{
			Id = "21_Neon_Deer",
			Index = 21,
			Name = "Neon Deer",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Passive ambient",
			Accent = "cyan",
			Secondary = "green",
			ModelName = "21_Neon_Deer",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/21_Neon_Deer",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/21_Neon_Deer/Neon_Deer.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/21_Neon_Deer/Neon_Deer.obj",
		},
		{
			Id = "22_Glow_Boar",
			Index = 22,
			Name = "Glow Boar",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Neutral",
			Accent = "orange",
			Secondary = "gold",
			ModelName = "22_Glow_Boar",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/22_Glow_Boar",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/22_Glow_Boar/Glow_Boar.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/22_Glow_Boar/Glow_Boar.obj",
		},
		{
			Id = "23_Crystal_Crab",
			Index = 23,
			Name = "Crystal Crab",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Passive shoreline",
			Accent = "cyan",
			Secondary = "pink",
			ModelName = "23_Crystal_Crab",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/23_Crystal_Crab",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/23_Crystal_Crab/Crystal_Crab.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/23_Crystal_Crab/Crystal_Crab.obj",
		},
		{
			Id = "24_Electric_Beetle",
			Index = 24,
			Name = "Electric Beetle",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Passive ambient",
			Accent = "gold",
			Secondary = "cyan",
			ModelName = "24_Electric_Beetle",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/24_Electric_Beetle",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/24_Electric_Beetle/Electric_Beetle.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/24_Electric_Beetle/Electric_Beetle.obj",
		},
		{
			Id = "25_Moon_Wolf",
			Index = 25,
			Name = "Moon Wolf",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Dangerous pack hunter",
			Accent = "white",
			Secondary = "blue",
			ModelName = "25_Moon_Wolf",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/25_Moon_Wolf",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/25_Moon_Wolf/Moon_Wolf.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/25_Moon_Wolf/Moon_Wolf.obj",
		},
		{
			Id = "26_Void_Spider",
			Index = 26,
			Name = "Void Spider",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Dangerous",
			Accent = "purple",
			Secondary = "magenta",
			ModelName = "26_Void_Spider",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/26_Void_Spider",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/26_Void_Spider/Void_Spider.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/26_Void_Spider/Void_Spider.obj",
		},
		{
			Id = "27_Lava_Scorpion",
			Index = 27,
			Name = "Lava Scorpion",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Dangerous",
			Accent = "red",
			Secondary = "orange",
			ModelName = "27_Lava_Scorpion",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/27_Lava_Scorpion",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/27_Lava_Scorpion/Lava_Scorpion.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/27_Lava_Scorpion/Lava_Scorpion.obj",
		},
		{
			Id = "28_Spirit_Elk",
			Index = 28,
			Name = "Spirit Elk",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Passive rare ambient",
			Accent = "green",
			Secondary = "white",
			ModelName = "28_Spirit_Elk",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/28_Spirit_Elk",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/28_Spirit_Elk/Spirit_Elk.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/28_Spirit_Elk/Spirit_Elk.obj",
		},
		{
			Id = "29_Sky_Ray",
			Index = 29,
			Name = "Sky Ray",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Passive flying ambient",
			Accent = "cyan",
			Secondary = "purple",
			ModelName = "29_Sky_Ray",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/29_Sky_Ray",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/29_Sky_Ray/Sky_Ray.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/29_Sky_Ray/Sky_Ray.obj",
		},
		{
			Id = "30_Ancient_Crystal_Golem",
			Index = 30,
			Name = "Ancient Crystal Golem",
			Category = "Wild",
			Tier = "Wild",
			Behavior = "Dangerous guardian",
			Accent = "cyan",
			Secondary = "gold",
			ModelName = "30_Ancient_Crystal_Golem",
			ModelPath = "Assets/Creatures/WildCreatures/Wild/30_Ancient_Crystal_Golem",
			FbxPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/30_Ancient_Crystal_Golem/Ancient_Crystal_Golem.fbx",
			ObjPath = "Roblox_NeonFantasyCreatures/WildCreatures/Wild/30_Ancient_Crystal_Golem/Ancient_Crystal_Golem.obj",
		},
	},
}
